# Generated by Django 6.0 on 2025-12-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_productmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num1', models.IntegerField(max_length=5)),
                ('num2', models.IntegerField(max_length=5)),
                ('result', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
