# Generated by Django 6.0 on 2025-12-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_storevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storevalue',
            name='num1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storevalue',
            name='num2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storevalue',
            name='result',
            field=models.BigIntegerField(),
        ),
    ]
